### ISSUE TITLE
关于entity2type.txt文件的问题

### ISSUE THREAD

**Issue by zmxdream** [thunlp/TKRL#4]
你好，我看了下entity2type.txt文件，按论文里面说构造type的时候没有去处FB15K的实体，为什么文件里实体数量只有14941,而不是14951，同时我看到有些行里面有多于一个的实体，一开始我以为是文件不规范，我把这些实体放到新行后，行数又多于14951,我有点困惑。希望您能指点一下，谢谢！

**Comment by Moringa9513** [comment]
> 你好，我看了下entity2type.txt文件，按论文里面说构造type的时候没有去处FB15K的实体，为什么文件里实体数量只有14941,而不是14951，同时我看到有些行里面有多于一个的实体，一开始我以为是文件不规范，我把这些实体放到新行后，行数又多于14951,我有点困惑。希望您能指点一下，谢谢！

您好，我也是遇到了和您类似的问题，可以私下相互沟通一下吗？我的邮箱是zhangfuxiang13@gmail.com
